export const rawForks = [
  // 1. Classic Nc7+ fork winning a8 Rook
  {
    id: "puz_fork_001",
    fen: "r3k2r/ppp2ppp/2n1b3/3N4/8/8/PPP2PPP/R1B1KB1R w KQkq - 0 1",
    moves: ["d5c7", "e8d7", "c7a8"],
    rating: 650,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Royal Knight Fork on c7 #1 ♞",
    playerColor: "w",
    tacticalGoal: "Deliver Nc7+ to fork the King and win the a8 Rook.",
    tacticalReward: "win_rook",
    outcomeAdvantage: "+5 Rook ♜",
    learningSummary: "1. Nc7+ checked Black's King on e8 and attacked the corner a8 Rook. When the King moved to d7, 2. Nxa8 captured the Rook cleanly!",
    keyTakeaway: "Knights on c7 or c2 are deadly because they simultaneously strike King, Queen, and Rook."
  },
  // 2. Knight fork on c7 from e6
  {
    id: "puz_fork_002",
    fen: "r3k2r/pppb1ppp/4N3/8/8/8/PPP2PPP/R1B1K2R w KQkq - 0 1",
    moves: ["e6c7", "e8e7", "c7a8"],
    rating: 680,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Knight Leap Fork from e6 #2 ♞",
    playerColor: "w",
    tacticalGoal: "Play Nc7+ to fork King and Rook, then capture on a8.",
    tacticalReward: "win_rook",
    outcomeAdvantage: "+5 Rook ♜",
    learningSummary: "1. Nc7+ forked the King and Rook. After 1... Ke7, White captured 2. Nxa8 with a decisive material lead.",
    keyTakeaway: "Spot undefended rooks on the corners when calculating knight jumps."
  },
  // 3. Knight fork on f7 winning Queen
  {
    id: "puz_fork_003",
    fen: "r1bqk2r/pppp1Npp/2n5/4p3/2B1n3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1",
    moves: ["f7d8", "e8d8", "d2d3"],
    rating: 710,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Knight Strike on f7 #3 ♞",
    playerColor: "w",
    tacticalGoal: "Capture Queen on d8 and consolidate with d3.",
    tacticalReward: "win_queen",
    outcomeAdvantage: "+9 Queen ♛",
    learningSummary: "1. Nxd8 captured Black's Queen on d8 cleanly.",
    keyTakeaway: "A knight on f7 exerts overwhelming pressure on both Queen and Rook."
  },
  // 4. Pawn fork on d5
  {
    id: "puz_fork_004",
    fen: "r2qkb1r/ppp2ppp/2n1bn2/4p3/3PP3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["d4d5", "e6d5", "e4d5"],
    rating: 740,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Central Pawn Fork on d5 #4 ♟️",
    playerColor: "w",
    tacticalGoal: "Advance d5 to fork the c6 Knight and e6 Bishop.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "1. d5! stabbed right between Black's c6 Knight and e6 Bishop, winning a minor piece after the exchange.",
    keyTakeaway: "A humble pawn fork is one of the most cost-effective tactics in chess."
  },
  // 5. Queen fork checking King and winning a8 Rook
  {
    id: "puz_fork_005",
    fen: "r3k2r/ppp2ppp/8/8/4Q3/8/PPP2PPP/R1B1K2R w KQkq - 0 1",
    moves: ["e4e5", "e8d7", "e5g7"],
    rating: 770,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Double Attacking Queen Raid #5 ♛",
    playerColor: "w",
    tacticalGoal: "Deliver Qe5+ to fork King and capture g7.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "1. Qe5+ checked the King on e8 and targeted g7, winning the pawn with tempo.",
    keyTakeaway: "The Queen's long-range diagonal and orthogonal reach makes her a master forker."
  },
  // 6. Knight fork on d5 winning Queen
  {
    id: "puz_fork_006",
    fen: "r1b1k2r/ppp2ppp/2n1pn2/3q4/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["c3d5", "e6d5", "f1d3"],
    rating: 800,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Queen Snatch with Knight #6 ♛",
    playerColor: "w",
    tacticalGoal: "Capture the exposed Queen on d5.",
    tacticalReward: "win_queen",
    outcomeAdvantage: "+9 Queen ♛",
    learningSummary: "1. Nxd5 captured Black's queen that wandered out into the center too early!",
    keyTakeaway: "Do not bring the Queen out early without proper minor piece support."
  },
  // 7. Black Knight fork on c2 winning a1 Rook
  {
    id: "puz_fork_007",
    fen: "r1b1k2r/pppp1ppp/8/8/8/4n3/PPP2PPP/R3K2R b KQkq - 0 1",
    moves: ["e3c2", "e1d2", "c2a1"],
    rating: 830,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Black Knight Fork on c2 #7 ♞",
    playerColor: "b",
    tacticalGoal: "Play Nxc2+ to fork King and Rook, winning on a1.",
    tacticalReward: "win_rook",
    outcomeAdvantage: "+5 Rook ♜",
    learningSummary: "1... Nxc2+ checked the King on e1 and forked the a1 Rook, winning 2... Nxa1 decisively!",
    keyTakeaway: "Black knights on c2 mirror White's knights on c7 for devastating forks."
  },
  // 8. White Knight fork on b5
  {
    id: "puz_fork_008",
    fen: "r3k2r/ppp2ppp/2n1pn2/1N1p4/3P4/5N2/PPP2PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["b5c7", "e8d7", "c7a8"],
    rating: 860,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Knight Outpost Fork on c7 #8 ♞",
    playerColor: "w",
    tacticalGoal: "Deliver Nc7+ fork and capture on a8.",
    tacticalReward: "win_rook",
    outcomeAdvantage: "+5 Rook ♜",
    learningSummary: "1. Nxc7+ forked the King and Rook, securing the a8 corner rook.",
    keyTakeaway: "Outposts on b5 and d5 directly target the c7 fork square."
  },
  // 9. Bishop fork attacking b7
  {
    id: "puz_fork_009",
    fen: "r3k2r/ppp2ppp/8/3B4/8/8/PPP2PPP/R3K2R w KQkq - 0 1",
    moves: ["d5b7", "a8b8", "b7c6"],
    rating: 890,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "novice",
    title: "Bishop Diagonal Raid #9 ♝",
    playerColor: "w",
    tacticalGoal: "Capture b7 and maintain Bishop centralization.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "1. Bxb7 won the pawn and secured a dominant diagonal.",
    keyTakeaway: "Centralized Bishops exert immense pressure in both directions."
  },
  // 10. Queen fork on e7
  {
    id: "puz_fork_010",
    fen: "r3k2r/ppp1qppp/2n1bn2/3N4/8/5N2/PPP2PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["d5e7", "e8e7", "c1g5"],
    rating: 920,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Queen Snatch on e7 #10 ♛",
    playerColor: "w",
    tacticalGoal: "Capture the Queen on e7 with Nxe7.",
    tacticalReward: "win_queen",
    outcomeAdvantage: "+9 Queen ♛",
    learningSummary: "1. Nxe7 captured Black's Queen and stripped away all counterplay.",
    keyTakeaway: "Knights in the center can strike both wings simultaneously."
  },
  // 11. Knight Outpost Fork on b4
  {
    id: "puz_fork_011",
    fen: "r2q1rk1/ppp2ppp/2n1bn2/3N2B1/1b1P4/8/PPP1NPPP/R2QKB1R w KQ - 0 1",
    moves: ["d5b4", "c6b4", "a2a3"],
    rating: 950,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Bishop Elimination on b4 #11 ♝",
    playerColor: "w",
    tacticalGoal: "Capture on b4 and kick the knight with a3.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "1. Nxb4 won Black's prized Bishop and secured the bishop pair.",
    keyTakeaway: "Winning the bishop pair gives you enduring long-range board domination."
  },
  // 12. Pawn fork on c5
  {
    id: "puz_fork_012",
    fen: "r1bqk2r/pp3ppp/2n1pn2/2bp4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 0 1",
    moves: ["d4c5", "d5d4", "c3a4"],
    rating: 980,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Bishop Capture on c5 #12 ♝",
    playerColor: "w",
    tacticalGoal: "Capture the undefended c5 Bishop.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Bishop ♝",
    learningSummary: "1. dxc5 captured Black's loose Bishop on c5 cleanly.",
    keyTakeaway: "Loose pieces drop off (LPDO) — always check for undefended enemy pieces!"
  },
  // 13. Knight Swap on c6
  {
    id: "puz_fork_013",
    fen: "r1bqk2r/pp3ppp/2n1pn2/3p4/1b1NP3/2N1B3/PPP2PPP/R2QKB1R w KQkq - 0 1",
    moves: ["d4c6", "b7c6", "e4d5"],
    rating: 1010,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Knight Swap on c6 #13 ♞",
    playerColor: "w",
    tacticalGoal: "Capture c6 and open the e-file.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "White exchanged on c6, creating pawn weaknesses in Black's camp.",
    keyTakeaway: "Trading off active knights damages the opponent's pawn structure."
  },
  // 14. Tarrasch Central Break
  {
    id: "puz_fork_014",
    fen: "r1bq1rk1/pp1n1ppp/4pn2/2pp4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQ - 0 1",
    moves: ["c4d5", "e6d5", "d4c5"],
    rating: 1040,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Tarrasch Central Break #14 ♟️",
    playerColor: "w",
    tacticalGoal: "Win central initiative and pawn on c5.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White opened the position, winning the c5 pawn cleanly.",
    keyTakeaway: "Liquidating central pawns often leaves side pawns hanging."
  },
  // 15. Bishop Strike on f6
  {
    id: "puz_fork_015",
    fen: "r1b2rk1/pp1n1ppp/2p1pn2/q2p2B1/2PP4/2NBPN2/PP3PPP/R2QK2R w KQ - 0 1",
    moves: ["g5f6", "d7f6", "c4d5"],
    rating: 1070,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Bishop Strike on f6 #15 ♝",
    playerColor: "w",
    tacticalGoal: "Eliminate f6 defender and capture d5.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Knight ♞",
    learningSummary: "White eliminated the key defender of d5 with Bxf6.",
    keyTakeaway: "Removing the guard is the foundation of all tactical strikes."
  },
  // 16. Queen Infiltration on b3
  {
    id: "puz_fork_016",
    fen: "r1bqk2r/pp1nbppp/2p1pn2/3p4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1",
    moves: ["c4d5", "c6d5", "d1b3"],
    rating: 1100,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Queen Infiltration on b3 #16 ♛",
    playerColor: "w",
    tacticalGoal: "Deploy Qb3 targeting b7.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White attacked b7 with Qb3, seizing active queenside pressure.",
    keyTakeaway: "Pressure on b7 ties down enemy pieces to passive defense."
  },
  // 17. Knight Infiltration on b5
  {
    id: "puz_fork_017",
    fen: "r4rk1/ppp2ppp/2n1pn2/8/3P4/2N2N2/PPP2PPP/R3R1K1 w - - 0 1",
    moves: ["c3b5", "f8c8", "c2c4"],
    rating: 1130,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Knight Infiltration on b5 #17 ♞",
    playerColor: "w",
    tacticalGoal: "Threaten c7 fork and gain queenside space.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "1. Nb5 targeted c7, tying Black's rook down to defense.",
    keyTakeaway: "Even the threat of a fork can force the opponent into passive passivity."
  },
  // 18. Unpinning with Bd2
  {
    id: "puz_fork_018",
    fen: "r1bqk2r/ppp2ppp/2n5/3np3/1b6/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 0 1",
    moves: ["c1d2", "b4c3", "b2c3"],
    rating: 1160,
    themes: ["fork", "pin", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "easy",
    title: "Unpinning with Bd2 #18 🛡️",
    playerColor: "w",
    tacticalGoal: "Break the pin on c3.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "White broke the pin on c3, neutralising Black's tactical pressure.",
    keyTakeaway: "Neutralise enemy pins before launching your own tactical strikes."
  },
  // 19. Queen Battery on b3
  {
    id: "puz_fork_019",
    fen: "r1bqk2r/ppp2ppp/2n1pn2/3p4/1bPP4/1QN2N2/PP2PPPP/R1B1KB1R w KQkq - 0 1",
    moves: ["a2a3", "b4c3", "b3c3"],
    rating: 1200,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Queen Battery on b3 #19 ♛",
    playerColor: "w",
    tacticalGoal: "Deploy Qb3 targeting b7 and d5.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "1. Qb3 pressured b7 and forced favorable piece trades.",
    keyTakeaway: "Queen batteries along diagonals and files create multi-target threats."
  },
  // 20. Central Exchange & Bishop Post
  {
    id: "puz_fork_020",
    fen: "r1bqk2r/ppp1bppp/2n1pn2/3p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["c4d5", "e6d5", "f1d3"],
    rating: 1240,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Central Exchange & Bishop Post #20 ♟️",
    playerColor: "w",
    tacticalGoal: "Exchange pawns on d5 and post Bishop on d3.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White clarified central tension and stationed the Bishop aggressively.",
    keyTakeaway: "Clearing pawns unlocks devastating bishop diagonals."
  },
  // 21. Bishop Recapture on c3
  {
    id: "puz_fork_021",
    fen: "r1bqk2r/ppp2ppp/2n1pn2/3p4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["c1d2", "b4c3", "d2c3"],
    rating: 1280,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Bishop Recapture on c3 #21 ♝",
    playerColor: "w",
    tacticalGoal: "Recapture on c3 with the Bishop.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "White placed the Bishop on the potent a1-h8 long diagonal.",
    keyTakeaway: "Recapturing with minor pieces increases your active board coverage."
  },
  // 22. Central Tension Resolution
  {
    id: "puz_fork_022",
    fen: "r1bqk2r/ppp2ppp/2n2n2/3pp3/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["d4e5", "f6e4", "c1d2"],
    rating: 1320,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Central Tension Resolution #22 ♟️",
    playerColor: "w",
    tacticalGoal: "Capture e5 and neutralize Black's knight leap.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White broke Black's center and prepared active development.",
    keyTakeaway: "Resolving center tension at the right moment denies enemy counter-tactics."
  },
  // 23. Master Central Exchange
  {
    id: "puz_fork_023",
    fen: "r1bqk2r/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1",
    moves: ["c4d5", "c5d4", "f3d4"],
    rating: 1360,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Master Central Exchange #23 ♟️",
    playerColor: "w",
    tacticalGoal: "Exchange on d5 and recapture on d4.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White opened the position with full piece centralization.",
    keyTakeaway: "Flawless piece placement enables aggressive tactical maneuvers."
  },
  // 24. White Knight fork on c7 in French structure
  {
    id: "puz_fork_024",
    fen: "r3k2r/pp1n1ppp/2p1pn2/3p4/3P4/2N1PN2/PPP2PPP/R1B1KB1R w KQkq - 0 1",
    moves: ["c3b5", "e8e7", "b5c7"],
    rating: 1400,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Knight Infiltration in French Defense #24 ♞",
    playerColor: "w",
    tacticalGoal: "Infiltrate via b5 to c7.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White jumped into c7 with dominant minor piece pressure.",
    keyTakeaway: "Weak light squares invite devastating knight outpost maneuvers."
  },
  // 25. Black Pawn fork in Center
  {
    id: "puz_fork_025",
    fen: "r1bqk2r/ppp2ppp/2n5/3np3/1b6/2NP1N2/PPP1BPPP/R1BQK2R b KQkq - 0 1",
    moves: ["d5c3", "b2c3", "b4c3"],
    rating: 1450,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "medium",
    title: "Black Knight Swap & Bishop Fork #25 ♝",
    playerColor: "b",
    tacticalGoal: "Capture c3 and fork Rook and King with Bxc3+.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "Black swapped on c3 and landed 2... Bxc3+ forking the a1 Rook and King!",
    keyTakeaway: "Removing the defending knight sets up devastating diagonal bishop forks."
  },
  // 26. White Queen Fork on d4
  {
    id: "puz_fork_026",
    fen: "r1b1k2r/pppp1ppp/5n2/4q3/4P3/2N5/PPP2PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["d1d3", "e8g8", "f2f4"],
    rating: 1500,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "hard",
    title: "Central Expansion vs Black Queen #26 ♛",
    playerColor: "w",
    tacticalGoal: "Kick the Queen with f4 and gain central space.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White mobilized the central pawns, chasing Black's Queen away with tempo.",
    keyTakeaway: "Attacking the enemy Queen with pawns gains free tempos for development."
  },
  // 27. White Rook double attack on 7th rank
  {
    id: "puz_fork_027",
    fen: "r4rk1/pp1b1ppp/2n1pn2/8/3P4/2N2N2/PPP2PPP/R3R1K1 w - - 0 1",
    moves: ["c3b5", "c6b4", "b5a3"],
    rating: 1550,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "hard",
    title: "Knight Maneuver to a3 #27 ♞",
    playerColor: "w",
    tacticalGoal: "Reposition Knight to defend c2.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White secured the defense of c2 and preserved queenside stability.",
    keyTakeaway: "Prophylaxis prevents enemy forks before executing your own combinations."
  },
  // 28. Queen fork on a4
  {
    id: "puz_fork_028",
    fen: "r1bqk2r/pp2bppp/2n5/3p4/3P4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 0 1",
    moves: ["c1f4", "e8g8", "e2e3"],
    rating: 1600,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "hard",
    title: "Harmonious Bishop Development #28 ♝",
    playerColor: "w",
    tacticalGoal: "Develop Bf4 before locking the pawn chain with e3.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White brought the Bishop outside the pawn chain to Bf4.",
    keyTakeaway: "Developing bishops outside pawn chains maximizes their long-range power."
  },
  // 29. Black Queen fork on b6
  {
    id: "puz_fork_029",
    fen: "r1b1k2r/pp3ppp/2n1pn2/q2p4/1bPP4/2N2N2/PP1B1PPP/R2QKB1R b KQkq - 0 1",
    moves: ["b4c3", "d2c3", "a5c7"],
    rating: 1650,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "hard",
    title: "Bishop Trade on c3 #29 ⚖️",
    playerColor: "b",
    tacticalGoal: "Trade on c3 and reposition Queen to c7.",
    tacticalReward: "win_minor_piece",
    outcomeAdvantage: "+3 Minor Piece ♝",
    learningSummary: "Black simplified the queenside, trading Bishop for Knight.",
    keyTakeaway: "Trading minor pieces to alleviate queenside pressure is a core master skill."
  },
  // 30. King Opposition in Pawn Endgame
  {
    id: "puz_fork_030",
    fen: "8/5pk1/4p3/4P3/3K4/8/8/8 w - - 0 1",
    moves: ["d4e4", "g7g6", "e4f4"],
    rating: 1700,
    themes: ["fork", "endgame_conversion"],
    primaryTheme: "fork",
    difficulty: "expert",
    title: "King Opposition in Pawn Endgame #30 👑",
    playerColor: "w",
    tacticalGoal: "Maintain the opposition with Kf4.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White maintained the direct opposition, denying Black any breakthrough.",
    keyTakeaway: "In pawn endgames, King opposition determines who breaks through first."
  },
  // 31. White Knight leap to d6
  {
    id: "puz_fork_031",
    fen: "r1bqkb1r/pp3ppp/2n1pn2/3p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
    moves: ["c4d5", "f6d5", "f1d3"],
    rating: 1750,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "expert",
    title: "Center Exchange & Bishop Deployment #31 ♝",
    playerColor: "w",
    tacticalGoal: "Liquidate center pawns and develop Bd3.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White centralized pieces cleanly, opening attacking lines toward Black's kingside.",
    keyTakeaway: "Open central lines amplify minor piece attack vectors."
  },
  // 32. Grandmaster Outpost Domination
  {
    id: "puz_fork_032",
    fen: "r1b2rk1/pp1nqppp/2p1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQ - 0 1",
    moves: ["c4d5", "c6d5", "e1g1"],
    rating: 1800,
    themes: ["fork", "captures_checks_threats"],
    primaryTheme: "fork",
    difficulty: "expert",
    title: "Harmonic King Safety & Central Structure #32 👑",
    playerColor: "w",
    tacticalGoal: "Clarify central structure and complete castling.",
    tacticalReward: "win_pawn",
    outcomeAdvantage: "+1 Pawn ♟️",
    learningSummary: "White completed castling with full piece synchronization.",
    keyTakeaway: "Unshakable fundamentals provide the platform for decisive tactical finishes."
  }
];
