import type { Square, PieceColor, PieceType } from "./models.js";
import type { StarRating } from "./scenario.js";
import type { PuzzleErrorCode, PuzzleErrorPayload } from "./errors.js";

/**
 * Comprehensive tactical and positional motif themes for curated puzzles.
 * Grouped into 5 pedagogical domains for structured chess learning.
/**
 * Canonical list of all tactical and positional puzzle themes.
 */
export const PUZZLE_THEMES = [
  // --- Domain 1: Fundamental Tactics ---
  "fork",
  "pin",
  "skewer",
  "discovered_attack",
  "discovered_check",
  "double_check",
  "hanging_piece",
  "trapped_piece",
  // --- Domain 2: Intermediate Tactical Motifs ---
  "captures_checks_threats", // CCT calculation discipline
  "knight_outpost",
  "cross_pin",
  "battery",
  "deflection",
  "decoy",
  "interference",
  "clearance",
  "greek_gift",
  "windmill",
  "zwischenzug", // In-between move
  "desperado",
  "overloaded_piece",
  "x_ray_attack",
  // --- Domain 3: Checkmate Pattern Families ---
  "mate_in_1",
  "mate_in_2",
  "mate_in_3",
  "mate_in_4",
  "mate_in_5",
  "back_rank_mate",
  "scholars_mate",
  "smothered_mate",
  "smothered",
  "anastasia_mate",
  "anastasia_hook",
  "arabian_mate",
  "hook_mate",
  "vukovic_mate",
  "boden_mate",
  "balestra_mate",
  "blackburne_mate",
  "lolli_mate",
  "damiano_mate",
  "kill_box_mate",
  "railroad_mate",
  "blind_swine_mate",
  "dovetail_mate",
  // --- Domain 4: Endgame Conversions ---
  "pawn_endgame",
  "rook_endgame",
  "queen_endgame",
  "minor_piece_endgame",
  "endgame_conversion",
  "promotion",
  "win_queen",
  "lucena_position",
  "philidor_defense",
  "two_bishops_mate",
  // --- Domain 5: Opening Traps & Defenses ---
  "legals_trap",
  "fried_liver",
  "noahs_ark_trap",
  "fools_mate",
] as const;

/**
 * Comprehensive tactical and positional motif themes for curated puzzles.
 * Grouped into 5 pedagogical domains for structured chess learning.
 */
export type PuzzleTheme = (typeof PUZZLE_THEMES)[number];

/**
 * High-level theme category for drill filtering.
 */
export type PuzzleThemeCategory =
  | "basic_tactics"
  | "advanced_tactics"
  | "checkmate_patterns"
  | "endgame_technique"
  | "opening_traps";

/**
 * Metadata descriptor for rendering theme cards in Themed Drills.
 */
export interface PuzzleThemeDescriptor {
  readonly id: PuzzleTheme;
  readonly category: PuzzleThemeCategory;
  readonly name: string;
  readonly icon: string;
  readonly description: string;
  readonly kidFriendlyTip: string;
  readonly estimatedRatingRange: readonly [number, number];
}

/**
 * Calibrated puzzle difficulty tier based on target ELO.
 */
export type PuzzleDifficultyTier =
  | "novice" // 600 - 900  (1-move captures / simple mate in 1)
  | "easy" // 900 - 1200 (2-ply forks, pins, simple mates)
  | "medium" // 1200 - 1500 (3-4 ply intermediate tactics)
  | "hard" // 1500 - 1800 (Complex multi-ply combinations)
  | "expert"; // 1800+       (Subtle sacrifices & endgame accuracy)

/**
 * Concrete pedagogical reward / tactical payoff expected from completing a puzzle.
 */
export type TacticalReward =
  | "checkmate"
  | "win_queen"
  | "win_rook"
  | "win_minor_piece"
  | "win_exchange"
  | "win_pawn"
  | "pawn_promotion"
  | "perpetual_defense"
  | "escape_danger";

/**
 * Turn-by-turn breakdown explaining individual plies in a multi-move solution.
 */
export interface PuzzleStepExplanation {
  /** 0-based ply index in puzzle.moves */
  readonly plyIndex: number;
  /** Standard Algebraic Notation of the move (e.g. "Nc7+", "Kd8", "Nxa8") */
  readonly moveSan: string;
  /** UCI move format (e.g. "b5c7") */
  readonly moveUci: string;
  /** Actor executing the move ('w' | 'b') */
  readonly actor: PieceColor;
  /** Kid-friendly explanation of the tactical purpose or consequence of this move */
  readonly explanation: string;
}

/**
 * Structured summary of net material advantage gained upon puzzle completion.
 */
export interface MaterialAdvantageSummary {
  /** Target piece captured or promoted (if applicable) */
  readonly pieceType?: PieceType;
  /** Net centipawn swing from player's perspective */
  readonly netCentipawns: number;
  /** Net standard point advantage (+9 Queen, +5 Rook, +3 Minor, +2 Exchange, +1 Pawn) */
  readonly netPoints: number;
  /** Human-readable pill label, e.g. "+5 Rook ♜", "+9 Queen ♛", "Checkmate 👑" */
  readonly formattedAdvantage: string;
  /** Whether the resulting material lead is completely decisive */
  readonly isDecisive: boolean;
}

/**
 * Full pedagogical analysis payload generated by PuzzleAnalysisEngine.
 */
export interface PuzzleAnalysisResult {
  /** Material balance in initial position */
  readonly initialMaterial: {
    readonly white: number;
    readonly black: number;
    readonly net: number;
  };
  /** Material balance in final position */
  readonly finalMaterial: {
    readonly white: number;
    readonly black: number;
    readonly net: number;
  };
  /** Net centipawn swing (final - initial from player's perspective) */
  readonly materialDeltaCentipawns: number;
  /** Net points gained (+9, +5, +3, etc.) */
  readonly netPointsDelta: number;
  /** Formatted advantage summary */
  readonly advantageSummary: MaterialAdvantageSummary;
  /** Primary tactical motif detected */
  readonly detectedTheme: PuzzleTheme;
  /** Whether solution ends in checkmate */
  readonly isCheckmate: boolean;
  /** Whether solution involves a pawn promotion */
  readonly isPawnPromotion: boolean;
  /** Catchy headline for the modal, e.g. "Royal Knight Fork on c7!" */
  readonly tacticalHeadline: string;
  /** 1-2 sentence kid-friendly explanation of why the tactic won */
  readonly kidFriendlyExplanation: string;
  /** Coach Sparky rule of thumb / takeaway tip */
  readonly ruleOfThumb: string;
  /** Detailed turn-by-turn narratives */
  readonly stepNarratives: readonly PuzzleStepExplanation[];
}

/**
 * Diagnostic analysis for an incorrect player move (refutation).
 */
export interface PlayerMistakeRefutation {
  /** Player's attempted move in UCI */
  readonly playerMoveUci: string;
  /** Player's attempted move in SAN */
  readonly playerMoveSan: string;
  /** Opponent's punishing counter-move in UCI */
  readonly refutationMoveUci: string;
  /** Opponent's punishing counter-move in SAN */
  readonly refutationMoveSan: string;
  /** Color of the punishing actor */
  readonly punishingActor: PieceColor;
  /** Piece lost or targeted in the mistake */
  readonly capturedPiece?: PieceType;
  /** Short tactical reason (e.g. "Leaves your Queen undefended") */
  readonly blunderReason: string;
  /** Kid-friendly coaching explanation */
  readonly kidFriendlyExplanation: string;
  /** Key square to highlight on board for the mistake warning */
  readonly threatSquare?: Square;
}

/**
 * Core immutable puzzle representation derived from curated offline positions.
 * Contains both structural move validation data and rich pedagogical metadata.
 */
export interface Puzzle {
  /** Unique puzzle identifier, e.g. "puz_fork_001" */
  readonly id: string;
  /** Initial board FEN position before the setup move or player move */
  readonly fen: string;
  /**
   * Solution line represented as standard UCI move strings (e.g. ["c3b5", "e8d8", "b5c7", "d8e7", "c7a8"]).
   */
  readonly moves: readonly string[];
  /** Calibrated difficulty rating (Elo / Glicko) */
  readonly rating: number;
  /** Rating deviation / confidence (Glicko RD) */
  readonly ratingDeviation: number;
  /** Identified tactical themes and motifs */
  readonly themes: readonly PuzzleTheme[];
  /** Primary theme of the puzzle for categorized drills */
  readonly primaryTheme: PuzzleTheme;
  /** Difficulty tier classification */
  readonly difficulty: PuzzleDifficultyTier;
  /** Kid-friendly puzzle title, e.g. "The Royal Knight Leap! ♞" */
  readonly title: string;
  /** Catchy subtitle or hint clue */
  readonly subtitle?: string;
  /** Side to move for the player ('w' | 'b') */
  readonly playerColor: PieceColor;
  /** Number of half-moves in the complete solution */
  readonly solutionPlies: number;

  // --- PEDAGOGICAL METADATA ---
  /**
   * Explicit tactical goal displayed in the HUD before and during play.
   * e.g. "Fork the King and Rook on c7 to win decisive material!"
   */
  readonly tacticalGoal: string;

  /**
   * The expected concrete payoff achieved by solving the puzzle.
   */
  readonly tacticalReward: TacticalReward;

  /**
   * Human-readable material / positional advantage descriptor.
   * e.g. "+5 Rook ♜", "+9 Queen ♛", "Checkmate 👑"
   */
  readonly outcomeAdvantage: string;

  /**
   * Post-solve coaching debrief explaining WHY the sequence won.
   * e.g. "1. Nb5 threatened c7. When Black's King moved, 2. Nxc7+ forked King and Rook, winning the undefended Rook!"
   */
  readonly learningSummary: string;

  /**
   * Coach rule of thumb or memorable guideline for young learners.
   * e.g. "Knights are master forkers because they can leap over defenders!"
   */
  readonly keyTakeaway: string;

  /**
   * Optional step-by-step breakdown for each move in the solution line.
   */
  readonly stepExplanations?: readonly PuzzleStepExplanation[];

  /**
   * Optional context describing the opponent's previous blunder that created this tactic.
   * e.g. "Black just moved their Knight to a5, leaving the c7 pawn unguarded."
   */
  readonly blunderContext?: string;

  /**
   * Key target squares involved in the tactic (e.g. ['c7', 'a8'] for fork and target rook).
   */
  readonly targetSquares?: readonly Square[];

  /**
   * Key pieces under threat or involved in the tactical motif.
   */
  readonly keySquares?: readonly Square[];
}

/**
 * Offline puzzle pack metadata header.
 */
export interface PuzzlePackMetadata {
  readonly version: string;
  readonly generatedAt: string;
  readonly totalPuzzles: number;
  readonly themeDistribution: Record<string, number>;
  readonly ratingDistribution: {
    readonly novice: number;
    readonly easy: number;
    readonly medium: number;
    readonly hard: number;
    readonly expert: number;
  };
}

/**
 * Complete offline bundle format loaded client-side.
 */
export interface PuzzleBundle {
  readonly metadata: PuzzlePackMetadata;
  readonly puzzles: readonly Puzzle[];
}

/**
 * Three progressive tiers of assistance designed for zero-frustration learning.
 */
export type HintLevel = 0 | 1 | 2 | 3;

export type HintTierName =
  "none" | "piece_nudge" | "target_glow" | "full_solution";

/**
 * Extended HintData supporting pedagogical context and vector visual overlays.
 */
export interface ExtendedHintData {
  /** Current active hint level (1, 2, or 3) */
  readonly level: HintLevel;
  /** Friendly tier name */
  readonly tier: HintTierName;
  /** Source square of the piece that should move (revealed in Tier 1+) */
  readonly sourceSquare?: Square;
  /** Destination target square (revealed in Tier 2+) */
  readonly targetSquare?: Square;
  /** Kid-friendly hint message explaining the concept */
  readonly message: string;
  /** Explicit tactical objective clue (e.g. "Look for a double attack on King and Rook") */
  readonly tacticalObjective?: string;
  /** Primary theme icon */
  readonly themeIcon?: string;
  /** Full algebraic move string (e.g. "Nf7#", revealed in Tier 3) */
  readonly solutionSan?: string;
  /** UCI move format (e.g. "d5f7", revealed in Tier 3) */
  readonly solutionUci?: string;
  /** Mascot dialogue accompanying the hint */
  readonly mascotDialogue?: string;
  /** Visual highlight vector arrow (from -> to) */
  readonly highlightArrow?: { readonly from: Square; readonly to: Square };
  /** Threat squares to highlight (e.g. attacked opponent pieces) */
  readonly threatSquares?: readonly Square[];
  /** Target squares to highlight (e.g. outpost or fork square) */
  readonly targetSquares?: readonly Square[];
}

/**
 * Structured hint payload returned to the UI when a hint is requested.
 * Backward-compatible alias of ExtendedHintData.
 */
export interface HintData extends ExtendedHintData {}

/**
 * Game modes available within the Puzzle Hub.
 */
export type PuzzleMode =
  "themed_drills" | "adaptive_ladder" | "puzzle_rush" | "streak_survivor";

/**
 * Result state for a single puzzle attempt within a session.
 */
export type PuzzleAttemptResult =
  | "unsolved"
  | "solved_first_try"
  | "solved_with_hints"
  | "solved_with_retries"
  | "failed";

/**
 * Base state for any active puzzle session.
 */
export interface BasePuzzleSessionState {
  readonly mode: PuzzleMode;
  readonly currentPuzzle: Puzzle | null;
  readonly currentFen: string;
  readonly currentMoveIndex: number;
  readonly isPlayerTurn: boolean;
  readonly isCompleted: boolean;
  readonly isSolvedSuccessfully: boolean;
  readonly attemptResult: PuzzleAttemptResult;
  readonly currentHintLevel: HintLevel;
  readonly activeHint: ExtendedHintData | null;
  readonly mistakesCount: number;
  readonly selectedSquare: Square | null;
  readonly legalMoves: readonly Square[];
  readonly lastMove: { readonly from: Square; readonly to: Square } | null;
  readonly isShaking: boolean;
  readonly feedbackMessage: string | null;
  readonly analysis: PuzzleAnalysisResult | null;
  readonly lastMistakeRefutation: PlayerMistakeRefutation | null;
}

/**
 * Themed Drills Session State (Untimed practice).
 */
export interface ThemedDrillsSessionState extends BasePuzzleSessionState {
  readonly mode: "themed_drills";
  readonly activeTheme: PuzzleTheme;
  readonly puzzlesSolvedInSession: number;
  readonly totalPuzzlesInTheme: number;
  readonly sessionAccuracyPercent: number;
}

/**
 * Adaptive Ladder Session State.
 */
export interface AdaptiveLadderSessionState extends BasePuzzleSessionState {
  readonly mode: "adaptive_ladder";
  readonly currentRating: number;
  readonly initialSessionRating: number;
  readonly ratingDelta: number;
  readonly ratingConfidence: number; // RD
  readonly streakCount: number;
  readonly bestStreakSession: number;
  readonly targetPuzzleRating: number;
}

/**
 * Puzzle Rush Session State (3-minute blitz sprint).
 */
export interface PuzzleRushSessionState extends BasePuzzleSessionState {
  readonly mode: "puzzle_rush";
  readonly timeRemainingSeconds: number;
  readonly initialTimeSeconds: number;
  readonly score: number;
  readonly strikes: number;
  readonly maxStrikes: number;
  readonly comboMultiplier: number;
  readonly currentStreak: number;
  readonly isTimerRunning: boolean;
  readonly isGameOver: boolean;
  readonly timeBonusEarnedSeconds: number;
}

/**
 * Streak Survivor Session State (Untimed 3-strike survival).
 */
export interface StreakSurvivorSessionState extends BasePuzzleSessionState {
  readonly mode: "streak_survivor";
  readonly livesRemaining: number;
  readonly maxLives: number;
  readonly currentStreak: number;
  readonly bestStreakAllTime: number;
  readonly score: number;
  readonly isGameOver: boolean;
}


/**
 * Historical rating adjustment point for charting.
 */
export interface RatingHistoryPoint {
  readonly timestamp: number;
  readonly rating: number;
  readonly puzzleId: string;
  readonly delta: number;
}

/**
 * Adaptive Elo Rating State for a young learner.
 */
export interface AdaptiveRatingState {
  readonly rating: number;
  readonly ratingDeviation: number;
  readonly peakRating: number;
  readonly totalAttempted: number;
  readonly totalSolved: number;
  readonly bestStreak: number;
  readonly ratingHistory: readonly RatingHistoryPoint[];
}

/**
 * Performance summary for a single puzzle theme.
 */
export interface ThemeMasteryProgress {
  readonly theme: PuzzleTheme;
  readonly attempted: number;
  readonly solved: number;
  readonly starsEarned: number;
  readonly masteryLevel: "novice" | "apprentice" | "master";
  readonly lastPracticedAt: number;
}

/**
 * Calculates user mastery level from total solved puzzles.
 * - master: >= 20 solved
 * - apprentice: >= 8 solved
 * - novice: < 8 solved
 */
export function calculateMasteryLevel(
  solved: number,
): "novice" | "apprentice" | "master" {
  if (solved >= 20) return "master";
  if (solved >= 8) return "apprentice";
  return "novice";
}

/**
 * High scores record for arcade modes.
 */
export interface PuzzleArcadeStats {
  readonly puzzleRushHighScore: number;
  readonly puzzleRushBestStreak: number;
  readonly streakSurvivorHighScore: number;
  readonly totalRushRuns: number;
}

/**
 * Record of solved puzzle completion.
 */
export interface SolvedPuzzleRecord {
  readonly stars: StarRating;
  readonly solvedAt: number;
}

/**
 * Overall persistent user progress across the entire Puzzle Hub.
 */
export interface PuzzleProgress {
  readonly ratingProfile: AdaptiveRatingState;
  readonly themeMastery: Record<string, ThemeMasteryProgress>;
  readonly arcadeStats: PuzzleArcadeStats;
  readonly solvedPuzzles: Record<string, SolvedPuzzleRecord>;
  readonly createdAt: number;
  readonly lastActiveAt: number;
}

/**
 * Storage abstraction for persisting Puzzle Hub progress.
 * Adheres to Rule 1 (I/O Isolation).
 */
export interface PuzzleProgressStore {
  getProgress(): Promise<PuzzleProgress>;
  updateRating(newRatingState: AdaptiveRatingState): Promise<void>;
  recordPuzzleAttempt(
    puzzleId: string,
    theme: PuzzleTheme,
    result: PuzzleAttemptResult,
    stars: StarRating,
  ): Promise<PuzzleProgress>;
  saveArcadeResult(
    mode: "puzzle_rush" | "streak_survivor",
    score: number,
    streak: number,
  ): Promise<PuzzleProgress>;
  /**
   * Complete lossless restoration of full Puzzle Hub progress.
   * Atomically sets ratingProfile, themeMastery, arcadeStats, and solvedPuzzles.
   */
  restoreProgress(progress: PuzzleProgress): Promise<void>;
  resetAll(): Promise<void>;
}

/**
 * Player move input action in puzzle engine.
 */
export interface PlayerMoveAction {
  readonly from: Square;
  readonly to: Square;
  readonly promotion?: "q" | "r" | "b" | "n";
}

/**
 * Result of validating a player's move against expected solution.
 */
export interface MoveValidationOutcome {
  readonly isCorrect: boolean;
  readonly isPuzzleComplete: boolean;
  readonly intermediateFen?: string;
  readonly nextFen: string;
  readonly botReplyMove?: {
    readonly from: Square;
    readonly to: Square;
    readonly promotion?: "q" | "r" | "b" | "n";
    readonly san: string;
    readonly uci: string;
  };
  readonly nextMoveIndex: number;
  readonly feedback: string;
  /** Pedagogical explanation for the move that was just played */
  readonly stepExplanation?: PuzzleStepExplanation;
  /** Refutation payload if player made an incorrect move */
  readonly refutation?: PlayerMistakeRefutation;
  /** Full analysis payload when puzzle completes */
  readonly analysis?: PuzzleAnalysisResult;
}

/**
 * Validates a player move against the current solution ply of a puzzle.
 * Pure function adhering to Rule 2.
 */
export interface PuzzleEngineService {
  validateMove(
    puzzle: Puzzle,
    currentMoveIndex: number,
    currentFen: string,
    playerMove: PlayerMoveAction,
  ): MoveValidationOutcome;

  generateHint(
    puzzle: Puzzle,
    currentMoveIndex: number,
    currentFen: string,
    requestedLevel: HintLevel,
  ): ExtendedHintData;

  calculatePuzzleStars(hintsUsed: number, mistakesCount: number): StarRating;

  analyzePuzzle?(puzzle: Puzzle): PuzzleAnalysisResult;

  explainPlayerMistake?(
    puzzle: Puzzle,
    currentMoveIndex: number,
    currentFen: string,
    playerMove: PlayerMoveAction,
  ): string;
}

/**
 * Parameters passed to the adaptive rating calculator.
 */
export interface RatingAdjustmentParams {
  readonly playerRating: number;
  readonly playerRd: number;
  readonly puzzleRating: number;
  readonly isSuccess: boolean;
  readonly hintsUsed: number;
  readonly currentStreak: number;
}

/**
 * Output of adaptive rating adjustment calculation.
 */
export interface RatingAdjustmentResult {
  readonly newRating: number;
  readonly newRd: number;
  readonly delta: number;
  readonly streakBonus: number;
  readonly isProtectedByFloor: boolean;
}

/**
 * Pure calculation functions for dynamic Elo progression tailored for kids.
 */
export interface AdaptiveRatingCalculator {
  calculateAdjustment(params: RatingAdjustmentParams): RatingAdjustmentResult;
  selectTargetPuzzleRating(currentRating: number, streak: number): number;
}

/**
 * Tick output for Puzzle Rush arcade countdown timer.
 */
export interface RushTickResult {
  readonly timeRemainingSeconds: number;
  readonly isExpired: boolean;
}

/**
 * Solve event output for Puzzle Rush streak and scoring.
 */
export interface RushSolveResult {
  readonly newScore: number;
  readonly newStreak: number;
  readonly comboMultiplier: number;
  readonly timeBonusSeconds: number;
  readonly isNewHighScore: boolean;
}

/**
 * Strike event output for Puzzle Rush / Survivor life tracking.
 */
export interface RushStrikeResult {
  readonly newStrikes: number;
  readonly isGameOver: boolean;
  readonly comboReset: boolean;
}

/**
 * Pure logic interface for managing Puzzle Rush arcade rules.
 */
export interface PuzzleRushRules {
  applySolve(
    currentScore: number,
    currentStreak: number,
    highScore: number,
    solveTimeMs: number,
  ): RushSolveResult;
  applyStrike(currentStrikes: number, maxStrikes?: number): RushStrikeResult;
  calculateTimeTick(
    currentSeconds: number,
    deltaSeconds: number,
  ): RushTickResult;
}

// Re-export error contracts for convenience
export type { PuzzleErrorCode, PuzzleErrorPayload };
