import json
import os
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PACKS_DIR = os.path.join(SCRIPT_DIR, "packs")
DATA_DIR = os.path.dirname(SCRIPT_DIR)
os.makedirs(PACKS_DIR, exist_ok=True)

def run_pack_validator(filename, var_name, puzzles):
    pack_mjs = os.path.join(PACKS_DIR, filename.replace('.json', '_pack.mjs'))
    with open(pack_mjs, 'w') as f:
        f.write(f"export const {var_name} = {json.dumps(puzzles, indent=2)};\n")
    
    json_path = os.path.join(DATA_DIR, filename)
    cmd = f"""node -e "
import {{ {var_name} }} from './apps/client/src/features/puzzles/data/scripts/packs/{filename.replace('.json', '_pack.mjs')}';
import {{ savePack }} from './apps/client/src/features/puzzles/data/scripts/validator.mjs';
savePack('{json_path}', {var_name});
" """
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=os.path.expanduser("~/works/projects/fun-chess"))
    if res.returncode != 0:
        print(f"❌ Error validating {filename}:")
        print(res.stderr or res.stdout)
        raise RuntimeError(f"Validation failed for {filename}")
    else:
        print(f"✅ {filename}: 100% PASS ({len(puzzles)} puzzles)")


# =========================================================================
# PACK 1: FORKS (32 Puzzles)
# =========================================================================
FORKS = [
    {
        "id": "puz_fork_001",
        "fen": "r3k2r/ppp2ppp/2n1b3/3N4/8/8/PPP2PPP/R1B1KB1R w KQkq - 0 1",
        "moves": ["d5c7", "e8d7", "c7a8"],
        "rating": 650,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Royal Knight Fork on c7 #1 ♞",
        "subtitle": "Deliver Nc7+ to fork King and a8 Rook!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Deliver Nc7+ to fork the King and win the a8 Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Nc7+ checked Black's King on e8 and attacked the corner a8 Rook. When the King moved to d7, 2. Nxa8 captured the Rook cleanly!",
        "keyTakeaway": "Knights on c7 or c2 are deadly because they simultaneously strike King and corner Rooks.",
        "targetSquares": ["c7", "a8"],
        "keySquares": ["d5", "c7"]
    },
    {
        "id": "puz_fork_002",
        "fen": "r3k2r/pppb1ppp/4N3/8/8/8/PPP2PPP/R1B1K2R w KQkq - 0 1",
        "moves": ["e6c7", "e8e7", "c7a8"],
        "rating": 680,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Knight Leap Fork from e6 #2 ♞",
        "subtitle": "Nc7+ strikes the King on e8 and Rook on a8!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Jump to c7 with check, winning the corner Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Nxc7+ checks the King on e8 while attacking a8. After 1...Ke7, White grabs the Rook with 2. Nxa8.",
        "keyTakeaway": "Look for undefended corner pieces when a Knight can land on the c7/c2 outposts.",
        "targetSquares": ["c7", "a8"],
        "keySquares": ["e6", "c7"]
    },
    {
        "id": "puz_fork_003",
        "fen": "r1b1k2r/ppp2ppp/8/8/8/4n3/PPPB1PPP/R3K2R b KQkq - 0 1",
        "moves": ["e3c2", "e1e2", "c2a1"],
        "rating": 710,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Black Knight Fork on c2 #3 ♞",
        "subtitle": "Black delivers ...Nc2+ to win White's a1 Rook!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Deliver ...Nc2+ to fork the King and win the a1 Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1...Nxc2+ delivered a royal fork against White's King and the corner a1 Rook. After 2. Ke2, Black played 2...Nxa1!",
        "keyTakeaway": "Black's Knight on c2 mirrors the power of White's Knight on c7.",
        "targetSquares": ["c2", "a1"],
        "keySquares": ["e3", "c2"]
    },
    {
        "id": "puz_fork_004",
        "fen": "r1bqk2r/pppp1ppp/8/2b1n3/4P3/2N5/PPPP1PPP/R1BQKBNR w KQkq - 0 1",
        "moves": ["d2d4", "c5d6", "d4e5"],
        "rating": 740,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Center Pawn Fork on d4 #4 ♟",
        "subtitle": "Push d4 to attack Bishop and Knight at once!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Advance the d-pawn to fork Black's minor pieces.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1. d4 attacked both Black's Bishop on c5 and Knight on e5. When the Bishop retreated to d6, White captured the Knight with 2. dxe5!",
        "keyTakeaway": "Pawns attacking two enemy pieces on the same rank guarantee winning a piece.",
        "targetSquares": ["d4", "e5"],
        "keySquares": ["d2", "d4"]
    },
    {
        "id": "puz_fork_005",
        "fen": "r1bqk2r/pppp1ppp/2n5/4p3/2B1N3/5N2/PPPP1PPP/R1BQK2R b KQkq - 0 1",
        "moves": ["d7d5", "c4d3", "d5e4"],
        "rating": 770,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Black Center Pawn Fork on d5 #5 ♟",
        "subtitle": "Strike in the center with ...d5 to fork White's pieces!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Push ...d5 to fork White's Bishop and Knight.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1...d5 struck the center, simultaneously attacking White's Bishop on c4 and Knight on e4, winning a full piece after 2. Bd3 dxe4.",
        "keyTakeaway": "The central pawn push ...d5 is a fundamental tactic against uncoordinated minor pieces.",
        "targetSquares": ["d5", "e4"],
        "keySquares": ["d7", "d5"]
    },
    {
        "id": "puz_fork_006",
        "fen": "r1bqk2r/pppp1ppp/8/8/2n5/2N5/PPP2PPP/R1BQ1RK1 w kq - 0 1",
        "moves": ["d1e2", "d8e7", "e2c4"],
        "rating": 800,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Queen Check Fork on e2 #6 ♛",
        "subtitle": "Qe2+ checks King and captures the loose Knight!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Play Qe2+ to check the King and pick up the unprotected Knight on c4.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1. Qe2+ attacked Black's King and the undefended Knight on c4. After Black blocked with 1...Qe7, White captured 2. Qxc4 cleanly!",
        "keyTakeaway": "Always check for loose pieces on the open board when you have a check available.",
        "targetSquares": ["e2", "c4"],
        "keySquares": ["d1", "e2"]
    },
    {
        "id": "puz_fork_007",
        "fen": "r1bqk2r/ppp2ppp/3p4/8/4N3/2P5/PP3PPP/R1BQK2R b KQkq - 0 1",
        "moves": ["d8e7", "d1e2", "e7e4"],
        "rating": 830,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Black Queen Central Strike #7 ♛",
        "subtitle": "Pin and fork on e-file with ...Qe7!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Pin and win the undefended Knight on e4 with ...Qe7.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1...Qe7 pinned White's Knight to the King on e1. Since the Knight could not escape, Black captured 2...Qxe4 next move.",
        "keyTakeaway": "A pin along an open file against the enemy King wins immobilized pieces.",
        "targetSquares": ["e7", "e4"],
        "keySquares": ["d8", "e7"]
    },
    {
        "id": "puz_fork_008",
        "fen": "r3k2r/p1p2ppp/8/3B4/8/8/PPP2PPP/R3K2R w KQkq - 0 1",
        "moves": ["d5c6", "e8e7", "c6a8"],
        "rating": 860,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Bishop Diagonal Fork on c6 #8 ♝",
        "subtitle": "Bc6+ attacks King on e8 and Rook on a8!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Play Bc6+ to fork the King and corner Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Bc6+ checked Black's King and sliced across to the unprotected a8 Rook. After 1...Ke7, 2. Bxa8 won the Rook!",
        "keyTakeaway": "Bishops on open diagonals can fork a centralized King and an undefended corner Rook.",
        "targetSquares": ["c6", "a8"],
        "keySquares": ["d5", "c6"]
    },
    {
        "id": "puz_fork_009",
        "fen": "r3k2r/ppp2ppp/8/8/3b4/8/P1P2PPP/R3K2R b KQkq - 0 1",
        "moves": ["d4c3", "e1e2", "c3a1"],
        "rating": 890,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "novice",
        "title": "Black Bishop Diagonal Skewer-Fork #9 ♝",
        "subtitle": "Deliver ...Bc3+ to fork King and a1 Rook!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Deliver ...Bc3+ to win White's corner Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1...Bc3+ checked White's King on e1 while aiming directly at the undefended a1 Rook, winning 2...Bxa1!",
        "keyTakeaway": "Long-range Bishops excel at attacking two distant pieces at once.",
        "targetSquares": ["c3", "a1"],
        "keySquares": ["d4", "c3"]
    },
    {
        "id": "puz_fork_010",
        "fen": "r4rk1/pp1q1ppp/8/3N4/8/8/PPP2PPP/R2Q1RK1 w - - 0 1",
        "moves": ["d5f6", "g7f6", "d1d7"],
        "rating": 920,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Knight Sacrifice Royal Fork #10 ♞",
        "subtitle": "Nf6+ checks King and uncovers the Queen!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Play Nf6+ to deflect Black's g-pawn and capture the Queen on d7.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1. Nf6+ checked Black's King and attacked the Queen on d7. After 1...gxf6, White captured 2. Qxd7 winning the Queen!",
        "keyTakeaway": "A check that attacks the enemy Queen must be answered, leaving the Queen vulnerable.",
        "targetSquares": ["f6", "d7"],
        "keySquares": ["d5", "f6"]
    },
    {
        "id": "puz_fork_011",
        "fen": "r2q1rk1/ppp2ppp/8/8/8/5n2/PP1Q1PPP/R3R1K1 b - - 0 1",
        "moves": ["f3d2", "e1e8", "f8e8"],
        "rating": 950,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Black Knight Discovered Strike #11 ♞",
        "subtitle": "Capture White's Queen on d2!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture White's Queen on d2 with the Knight.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1...Nxd2 captured White's Queen on d2. When White tried 2. Rxe8+, Black recaptured 2...Rxe8 remaining up a full Queen.",
        "keyTakeaway": "Tactical strikes that win the enemy Queen decide the game immediately.",
        "targetSquares": ["d2", "e8"],
        "keySquares": ["f3", "d2"]
    },
    {
        "id": "puz_fork_012",
        "fen": "r1bqk2r/ppppbppp/2n5/4N3/4n3/2N5/PPPP1PPP/R1BQKB1R w KQkq - 0 1",
        "moves": ["e5c6", "b7c6", "c3e4"],
        "rating": 980,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Knight Trade into Piece Win #12 ♞",
        "subtitle": "Trade on c6 and capture the undefended e4 Knight!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Trade on c6 and capture the undefended e4 Knight.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1. Nxc6 removed Black defender on c6. After 1...bxc6, White captured 2. Nxe4 cleanly.",
        "keyTakeaway": "Removing the defender allows you to win hanging enemy pieces.",
        "targetSquares": ["c6", "e4"],
        "keySquares": ["e5", "c3"]
    },
    {
        "id": "puz_fork_013",
        "fen": "r3k2r/ppp2ppp/8/3Q4/8/8/PPP2PPP/R3K2R w KQkq - 0 1",
        "moves": ["d5e5", "e8d8", "e5g7"],
        "rating": 1020,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Central Queen Double Attack #13 ♛",
        "subtitle": "Qe5+ checks King and targets g7!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Check the King with Qe5+ and capture the g7 pawn with tempo.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Pawn ♟",
        "learningSummary": "1. Qe5+ forced Black's King to d8, and White followed up with 2. Qxg7 attacking the h8 Rook!",
        "keyTakeaway": "Centralized Queens dominate the board by creating threats on both flanks simultaneously.",
        "targetSquares": ["e5", "g7"],
        "keySquares": ["d5", "e5"]
    },
    {
        "id": "puz_fork_014",
        "fen": "r2qk2r/ppp2ppp/8/3n1b2/4P3/8/PPP2PPP/R1BQK2R w KQkq - 0 1",
        "moves": ["e4f5", "d8e7", "d1e2"],
        "rating": 1060,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Central Pawn Breakthrough Fork #14 ♟",
        "subtitle": "Win a minor piece with the e4 pawn fork!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the piece on f5 and consolidate with Qe2.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1. exf5 captured Black's Bishop. After 1...Qe7+, White blocked calmly with 2. Qe2 maintaining the piece advantage.",
        "keyTakeaway": "When ahead material from a fork, trading Queens neutralizes opponent counterplay.",
        "targetSquares": ["f5", "e2"],
        "keySquares": ["e4", "f5"]
    },
    {
        "id": "puz_fork_015",
        "fen": "r1bqk2r/ppp2ppp/8/8/4p3/3N1B2/PPP2PPP/R1BQK2R b KQkq - 0 1",
        "moves": ["e4f3", "d1f3", "e8g8"],
        "rating": 1100,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Black Pawn Strike on f3 #15 ♟",
        "subtitle": "Capture White's Bishop and castle safely!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture White's Bishop with ...exf3 and castle to safety.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1...exf3 captured White's Bishop. After White recaptured 2. Qxf3, Black castled 2...O-O with a solid extra piece.",
        "keyTakeaway": "After winning material with a pawn fork, bring your King to safety right away.",
        "targetSquares": ["f3", "g8"],
        "keySquares": ["e4", "f3"]
    },
    {
        "id": "puz_fork_016",
        "fen": "r3k2r/ppp2ppp/4b3/2N5/8/8/PPP2PPP/R1B1K2R w KQkq - 0 1",
        "moves": ["c5e6", "f7e6", "c1e3"],
        "rating": 1140,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Bishop Snatch with Knight #16 ♞",
        "subtitle": "Nxe6 captures Black Bishop and weakens pawns!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the bishop on e6 and develop safely.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. Nxe6 won the active Bishop on e6, damaging Black pawn structure.",
        "keyTakeaway": "Exchanging an active Knight for a defending Bishop damages enemy structure.",
        "targetSquares": ["e6", "e3"],
        "keySquares": ["c5", "e6"]
    },
    {
        "id": "puz_fork_017",
        "fen": "r2q1r2/ppp2pkp/4N3/8/8/8/PPP2PPP/R1B1K2R w KQ - 0 1",
        "moves": ["e6d8", "f8d8", "c1e3"],
        "rating": 1180,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "easy",
        "title": "Royal Fork Payoff on d8 #17 ♞",
        "subtitle": "Collect the Queen after the royal fork!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the Queen on d8 and develop the Bishop to e3.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1. Nxd8 captured Black's Queen cleanly. After 1...Raxd8, White developed 2. Be3 with an overwhelming material lead.",
        "keyTakeaway": "When a royal fork hits King and Queen, grab the Queen without hesitation.",
        "targetSquares": ["d8", "e3"],
        "keySquares": ["e6", "d8"]
    },
    {
        "id": "puz_fork_018",
        "fen": "r1b1k2r/ppp2ppp/8/8/8/4n3/PPP2PPP/R2Q1RK1 b kq - 0 1",
        "moves": ["e3d1", "f1d1", "e8g8"],
        "rating": 1220,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Black Royal Fork Payoff #18 ♞",
        "subtitle": "Snag White's Queen on d1 and castle!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture White's Queen on d1 and secure King safety.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1...Nxd1 captured White's Queen. After 2. Rxd1, Black castled 2...O-O maintaining an easy win.",
        "keyTakeaway": "Material superiority simplifies the endgame to a straightforward victory.",
        "targetSquares": ["d1", "g8"],
        "keySquares": ["e3", "d1"]
    },
    {
        "id": "puz_fork_019",
        "fen": "r4rk1/ppp2ppp/8/3B4/8/8/PPP2PPP/R3K2R w KQ - 0 1",
        "moves": ["d5b7", "a8b8", "b7f3"],
        "rating": 1260,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Bishop Queenside Snack on b7 #19 ♝",
        "subtitle": "Bxb7 attacks Rook and wins a key pawn!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the b7 pawn and retreat the Bishop safely to f3.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Pawn ♟",
        "learningSummary": "1. Bxb7 won Black's b7 pawn and attacked the a8 Rook. After 1...Rab8, White preserved the Bishop on 2. Bf3.",
        "keyTakeaway": "Active Bishops on open diagonals can snatch pawns and retreat safely.",
        "targetSquares": ["b7", "f3"],
        "keySquares": ["d5", "b7"]
    },
    {
        "id": "puz_fork_020",
        "fen": "r4k2/pppN1ppp/8/2q5/8/8/PPP2PPP/R1B1K2R w KQ - 0 1",
        "moves": ["d7c5", "f8e7", "c5b3"],
        "rating": 1300,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Royal Knight Leap on c5 #20 ♞",
        "subtitle": "Capture the Queen on c5 and retreat to safety!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the enemy Queen on c5 with the Knight.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1. Nxc5 captured Black's Queen after the check on d7, leaving White completely winning.",
        "keyTakeaway": "Executing the second half of a tactic cleanly is just as vital as finding the initial fork.",
        "targetSquares": ["c5", "b3"],
        "keySquares": ["d7", "c5"]
    },
    {
        "id": "puz_fork_021",
        "fen": "r1b1k2r/ppp2ppp/8/8/2Q5/8/PPPn1PPP/R3K2R b KQkq - 0 1",
        "moves": ["d2c4", "e1e2", "c4b2"],
        "rating": 1340,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Black Knight Snaps Queen on c4 #21 ♞",
        "subtitle": "Take the Queen on c4 and grab the b2 pawn!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture White's Queen on c4 and gobble the b2 pawn.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1...Nxc4 captured White's Queen. After 2. Ke2, Black grabbed 2...Nxb2 for extra measure.",
        "keyTakeaway": "A well-placed Knight inside the enemy camp wreaks havoc on major pieces.",
        "targetSquares": ["c4", "b2"],
        "keySquares": ["d2", "c4"]
    },
    {
        "id": "puz_fork_022",
        "fen": "r2q1rk1/1ppn1ppp/1N6/8/8/8/PPP2PPP/R1B1K2R w KQ - 0 1",
        "moves": ["b6a8", "d8a8", "e1g1"],
        "rating": 1380,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Knight Infiltration on a8 #22 ♞",
        "subtitle": "Capture the corner a8 Rook and castle!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Take the corner Rook on a8 and castle to safety.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Nxa8 captured Black's corner Rook. After 1...Qxa8, White castled 2. O-O with a decisive material lead.",
        "keyTakeaway": "Securing material and then castling prevents any desperate counter-attacks.",
        "targetSquares": ["a8", "g1"],
        "keySquares": ["b6", "a8"]
    },
    {
        "id": "puz_fork_023",
        "fen": "r3k2r/p1p2ppp/2n5/1B6/8/8/PPP2PPP/R1B1K2R w KQkq - 0 1",
        "moves": ["b5c6", "e8e7", "c6a8"],
        "rating": 1420,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Bishop Fork Win on a8 #23 ♝",
        "subtitle": "Bxc6+ forks King and wins the a8 Rook!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Play Bxc6+ to fork King and capture the a8 Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Bxc6+ checked the King and won the corner a8 Rook cleanly.",
        "keyTakeaway": "Pinning and attacking along the long diagonal forces heavy material gains.",
        "targetSquares": ["c6", "a8"],
        "keySquares": ["b5", "c6"]
    },
    {
        "id": "puz_fork_024",
        "fen": "r1b1k2r/ppp2ppp/8/4q3/8/8/PNN2PPP/R4RK1 b kq - 0 1",
        "moves": ["e5b2", "f1b1", "b2f6"],
        "rating": 1460,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "medium",
        "title": "Black Queen Infiltration on b2 #24 ♛",
        "subtitle": "Capture the b2 Knight and retreat to f6!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the Knight on b2 and retreat safely.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1...Qxb2 grabbed White's unprotected Knight on b2, and after 2. Rfb1, Black retreated 2...Qf6 safely.",
        "keyTakeaway": "Always ensure your Queen has an escape route after capturing in enemy territory.",
        "targetSquares": ["b2", "f6"],
        "keySquares": ["e5", "b2"]
    },
    {
        "id": "puz_fork_025",
        "fen": "r2q1rk1/pp1b1ppp/3p4/4nN2/8/8/PPP2PPP/R1BQR1K1 w - - 0 1",
        "moves": ["f5d6", "d8f6", "d6e4"],
        "rating": 1500,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "hard",
        "title": "Knight Outpost Double Attack on d6 #25 ♞",
        "subtitle": "Nxd6 attacks Queen and Bishop!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Win the d6 pawn and reposition the Knight on e4.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Pawn ♟",
        "learningSummary": "1. Nxd6 won the isolated d6 pawn and attacked both e5 and d7. After 1...Qf6, White repositioned 2. Ne4.",
        "keyTakeaway": "Outpost Knights in the enemy center control vital escape squares and target weak pawns.",
        "targetSquares": ["d6", "e4"],
        "keySquares": ["f5", "d6"]
    },
    {
        "id": "puz_fork_026",
        "fen": "r2q1rk1/pppb1ppp/2N5/8/8/8/PPP2PPP/R1B1R1K1 w - - 0 1",
        "moves": ["c6d8", "a8d8", "c1f4"],
        "rating": 1550,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "hard",
        "title": "Knight Decapitation on d8 #26 ♞",
        "subtitle": "Take Black's Queen on d8 and develop Bf4!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the Queen on d8 and activate the dark-squared Bishop.",
        "tacticalReward": "win_queen",
        "outcomeAdvantage": "+9 Queen ♛",
        "learningSummary": "1. Nxd8 eliminated Black's Queen. After 1...Raxd8, White activated 2. Bf4 with overwhelming endgame control.",
        "keyTakeaway": "Trading down when ahead in material transitions directly into an easily won endgame.",
        "targetSquares": ["d8", "f4"],
        "keySquares": ["c6", "d8"]
    },
    {
        "id": "puz_fork_027",
        "fen": "r3k2r/ppp2ppp/4b3/3N4/8/8/PPP2PPP/R3K2R w KQkq - 0 1",
        "moves": ["d5c7", "e8e7", "c7a8"],
        "rating": 1600,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "hard",
        "title": "Outpost Knight Fork on c7 #27 ♞",
        "subtitle": "Nc7+ forks King and wins the a8 Rook!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Deliver Nc7+ to fork King and Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Nc7+ forked the King and corner Rook cleanly.",
        "keyTakeaway": "Active knights in open positions strike both flanks effortlessly.",
        "targetSquares": ["c7", "a8"],
        "keySquares": ["d5", "c7"]
    },
    {
        "id": "puz_fork_028",
        "fen": "r1bqk2r/pppp1ppp/8/3Np3/1bBnP3/3P1N2/PPP2PPP/R1BQK2R w KQkq - 0 1",
        "moves": ["d5b4", "d4f3", "d1f3"],
        "rating": 1650,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "hard",
        "title": "Tactical Piece Snatch on b4 #28 ♞",
        "subtitle": "Nxb4 wins Black's exposed Bishop!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the loose Bishop on b4 and recapture on f3 with the Queen.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Minor Piece ⚔️",
        "learningSummary": "1. Nxb4 won Black's loose Bishop on b4. After 1...Nxf3+, White recaptured 2. Qxf3 defending with an extra piece.",
        "keyTakeaway": "Tactical calculation must verify all opponent intermediate checks before capturing.",
        "targetSquares": ["b4", "f3"],
        "keySquares": ["d5", "b4"]
    },
    {
        "id": "puz_fork_029",
        "fen": "r3k2r/ppp2ppp/8/8/4Q3/8/PPP2PPP/R3K2R w KQkq - 0 1",
        "moves": ["e4b7", "e8g8", "b7a8"],
        "rating": 1700,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "hard",
        "title": "Queen Fork Infiltration on b7 #29 ♛",
        "subtitle": "Qxb7 attacks the a8 Rook and wins material!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture on b7 and win the a8 Rook.",
        "tacticalReward": "win_rook",
        "outcomeAdvantage": "+5 Rook ♜",
        "learningSummary": "1. Qxb7 attacked Black corner Rook. When Black castled 1...O-O, White captured 2. Qxa8.",
        "keyTakeaway": "Queens invading the 7th rank quickly gobble up loose pieces.",
        "targetSquares": ["b7", "a8"],
        "keySquares": ["e4", "b7"]
    },
    {
        "id": "puz_fork_030",
        "fen": "4k3/pp3ppp/5N2/8/8/8/PPP2PPP/4K3 w - - 0 1",
        "moves": ["f6h7", "f7f6", "e1e2"],
        "rating": 1820,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "expert",
        "title": "Endgame Flank Knight Raid on h7 #30 ♞",
        "subtitle": "Nxh7 grabs a kingside pawn with check!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the h7 pawn and march the King forward to support.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Passed Pawn ♟",
        "learningSummary": "1. Nxh7 snatched a crucial kingside pawn with check. When Black played 1...f6 to trap the Knight, White brought the King 2. Ke2.",
        "keyTakeaway": "In Knight endgames, outside passed pawns created by flank captures decide the race.",
        "targetSquares": ["h7", "e2"],
        "keySquares": ["f6", "h7"]
    },
    {
        "id": "puz_fork_031",
        "fen": "r7/ppp2pkp/8/8/3Q4/8/PPP2PPP/R5K1 w - - 0 1",
        "moves": ["d4e5", "g7g8", "e5c7"],
        "rating": 1870,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "expert",
        "title": "Major Piece Infiltration on c7 #31 ♛",
        "subtitle": "Qe5+ drives the King away to win c7!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Deliver Qe5+ and capture the defenseless c7 pawn.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Decisive Pawn ♟",
        "learningSummary": "1. Qe5+ checked Black's King on g7, and after 1...Kg8, White captured 2. Qxc7 establishing a winning Queen outpost.",
        "keyTakeaway": "A centralized Queen that gives check before capturing pawns prevents opponent counter-checks.",
        "targetSquares": ["e5", "c7"],
        "keySquares": ["d4", "e5"]
    },
    {
        "id": "puz_fork_032",
        "fen": "r4k2/ppp2ppp/8/3N4/8/8/PPP2PPP/4K3 w - - 0 1",
        "moves": ["d5c7", "a8c8", "c7b5"],
        "rating": 1950,
        "ratingDeviation": 80,
        "themes": ["fork", "captures_checks_threats"],
        "primaryTheme": "fork",
        "difficulty": "expert",
        "title": "Endgame Knight Pawn Fork on c7 #32 ♞",
        "subtitle": "Nxc7 wins a vital pawn and retreats safely!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture the c7 pawn and reposition the Knight to b5.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Passed Pawn ♟",
        "learningSummary": "1. Nxc7 won the c7 pawn. After 1...Rc8, White repositioned 2. Nb5 safely.",
        "keyTakeaway": "In minor piece endgames, every extra pawn counts toward promotion.",
        "targetSquares": ["c7", "b5"],
        "keySquares": ["d5", "c7"]
    }
]

run_pack_validator('forks.json', 'FORK_DATA', FORKS)


# =========================================================================
# PACK 2: PINS (32 Puzzles)
# =========================================================================
PINS = [
    {
        "id": "puz_pin_001",
        "fen": "r1bqk2r/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
        "moves": ["b5c6", "d7c6", "f3e5"],
        "rating": 650,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Ruy Lopez Classical Pin on c6 #1 📌",
        "subtitle": "Pin the c6 Knight and win the e5 pawn!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Pin and capture on c6, then win the e5 pawn.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1. Bxc6 pinned and captured the Knight on c6. After 1...dxc6, White snatched 2. Nxe5 with an extra center pawn.",
        "keyTakeaway": "Pinning the defender of a central pawn allows you to capture the pawn once the defender is removed.",
        "targetSquares": ["c6", "e5"],
        "keySquares": ["b5", "c6"]
    },
    {
        "id": "puz_pin_002",
        "fen": "r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
        "moves": ["b5c6", "b7c6", "f3e5"],
        "rating": 680,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Absolute Knight Pin on c6 #2 📌",
        "subtitle": "Eliminate the pinned defender on c6!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Remove the pinned c6 Knight to win the e5 pawn.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1. Bxc6 removed the pinned defender. After 1...bxc6, White captured the unguarded 2. Nxe5 pawn.",
        "keyTakeaway": "A pinned piece cannot effectively defend other friendly pieces.",
        "targetSquares": ["c6", "e5"],
        "keySquares": ["b5", "c6"]
    },
    {
        "id": "puz_pin_003",
        "fen": "r1bqk2r/ppp2ppp/2n1pn2/3p4/1bPP4/2N1PN2/PP1B1PPP/R2QKB1R w KQkq - 0 1",
        "moves": ["c3d5", "e6d5", "d2b4"],
        "rating": 710,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Unpinning into Bishop Capture #3 📌",
        "subtitle": "Unpin the Knight on c3 to win the b4 Bishop!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Resolve the pin on c3 and win Black's b4 Bishop.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. Nxd5 resolved the pin on c3 by jumping into the center. After 1...exd5, White captured 2. Bxb4 cleanly!",
        "keyTakeaway": "When an opponent pins your piece, look for tactical counter-strikes that unpin with threats.",
        "targetSquares": ["d5", "b4"],
        "keySquares": ["c3", "d2"]
    },
    {
        "id": "puz_pin_004",
        "fen": "r1bqk2r/ppp2ppp/2n1pn2/8/1b1P4/2N2N2/PPP1BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c1g5", "h7h6", "g5f6"],
        "rating": 740,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Relative Bishop Pin on f6 #4 📌",
        "subtitle": "Pin the f6 Knight to the Queen and capture!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Pin the f6 Knight to Black's Queen with Bg5 and exchange.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. Bg5 pinned Black's f6 Knight against the d8 Queen. After 1...h6, White captured 2. Bxf6 winning the knight.",
        "keyTakeaway": "A relative pin against the Queen severely restricts the pinned piece's mobility.",
        "targetSquares": ["g5", "f6"],
        "keySquares": ["c1", "g5"]
    },
    {
        "id": "puz_pin_005",
        "fen": "r1bqk2r/ppp2ppp/2n2n2/3pp3/1b1P4/2N1PN2/PPP1BPPP/R1BQK2R b KQkq - 0 1",
        "moves": ["c8g4", "d4e5", "g4f3"],
        "rating": 770,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Black Bishop Pin on g4 #5 📌",
        "subtitle": "Pin White's f3 Knight and eliminate it!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Pin the f3 Knight with ...Bg4 and capture it after central pawn moves.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1...Bg4 pinned the f3 Knight to White's Queen. After 2. dxe5, Black captured 2...Bxf3 removing the defender.",
        "keyTakeaway": "Pinning f3 or f6 paralyzes the key guardian of the center.",
        "targetSquares": ["g4", "f3"],
        "keySquares": ["c8", "g4"]
    },
    {
        "id": "puz_pin_006",
        "fen": "r1bqk2r/pppp1ppp/2n2n2/1B2p3/3PP3/5N2/PPP2PPP/RNBQK2R w KQkq - 0 1",
        "moves": ["d4d5", "c6e7", "f3e5"],
        "rating": 800,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Pawn Advance Against Pinned Knight #6 ♟",
        "subtitle": "Push d5 to exploit the pinned c6 Knight!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Advance d5 to drive the pinned Knight and win e5.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1. d5 attacked the pinned c6 Knight. When it was forced to retreat 1...Ne7, White won 2. Nxe5.",
        "keyTakeaway": "Always attack pinned pieces with pawns to gain space and force concessions.",
        "targetSquares": ["d5", "e5"],
        "keySquares": ["d4", "d5"]
    },
    {
        "id": "puz_pin_007",
        "fen": "r1bqk2r/ppp2ppp/2n2n2/3p4/1b1PP3/2N2N2/PPP1BPPP/R1BQK2R b KQkq - 0 1",
        "moves": ["f6e4", "c1d2", "e4d2"],
        "rating": 830,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Black Central Pawn Thrust #7 ♟",
        "subtitle": "Advance ...e4 to drive the pinned f3 Knight!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Push ...e4 and capture the loose d4 pawn.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1...e4 drove White's Knight to d2, allowing Black to capture 2...Nxd4 in the center.",
        "keyTakeaway": "Advancing pawns on pinned pieces wins central territory and opens attack lines.",
        "targetSquares": ["e4", "d4"],
        "keySquares": ["e5", "e4"]
    },
    {
        "id": "puz_pin_008",
        "fen": "r1bqk2r/ppp2ppp/2n5/3p4/3Pn3/2N2N2/PPP1BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["e1g1", "e8g8", "c3e4"],
        "rating": 860,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Castling Out of Pin into Central Capture #8 🏰",
        "subtitle": "Castle to safety and capture the e4 Knight!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Castle safely and capture Black's advanced e4 Knight.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. O-O unpinned the King, and after 1...O-O, White captured the knight 2. Nxe4.",
        "keyTakeaway": "Castling breaks vertical pins on the e-file and prepares active counterplay.",
        "targetSquares": ["g1", "e4"],
        "keySquares": ["e1", "g1"]
    },
    {
        "id": "puz_pin_009",
        "fen": "r1bqk2r/ppp1bppp/2n5/1B1p4/3P4/2N2N2/PPP2PPP/R1BQK2R w KQkq - 0 1",
        "moves": ["f3e5", "c8d7", "e5d7"],
        "rating": 890,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "novice",
        "title": "Piling On the Pinned Knight #9 ♞",
        "subtitle": "Ne5 increases pressure on the pinned c6 Knight!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Play Ne5 to overload the pinned c6 Knight.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. Ne5 added a second attacker to the pinned c6 Knight. After 1...Bd7, White captured 2. Nxd7 winning the Bishop pair.",
        "keyTakeaway": "Add attackers to a pinned piece until the defense collapses.",
        "targetSquares": ["e5", "d7"],
        "keySquares": ["f3", "e5"]
    },
    {
        "id": "puz_pin_010",
        "fen": "r2qk2r/pppb1ppp/2n1pn2/3p4/3P4/2N1PN2/PPP1BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["e1g1", "e8g8", "f1e1"],
        "rating": 920,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Rook Alignment on e-File #10 ♜",
        "subtitle": "Prepare the absolute pin on the e-file!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Castle and place the Rook on e1 to prepare e-file pins.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 King Safety 🏰",
        "learningSummary": "1. O-O and 2. Re1 lined up White's Rook against Black's King for future tactical pins.",
        "keyTakeaway": "Place Rooks on open and half-open files opposite enemy Kings.",
        "targetSquares": ["g1", "e1"],
        "keySquares": ["e1", "f1"]
    },
    {
        "id": "puz_pin_011",
        "fen": "r1bqk2r/ppp2ppp/2n5/3pP3/1b1P4/2N2N2/PPP3PP/R1BQKB1R w KQkq - 0 1",
        "moves": ["c1d2", "b4c3", "d2c3"],
        "rating": 950,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Neutralizing the Pin with Bd2 #11 ♝",
        "subtitle": "Bd2 blocks the pin and recaptures cleanly!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Block the pin with Bd2 and recapture on c3.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. Bd2 neutralized Black's pin on the c3 Knight. When Black played 1...Bxc3, White recaptured 2. Bxc3 maintaining harmony.",
        "keyTakeaway": "Interposing a Bishop is the standard technique to break a pin.",
        "targetSquares": ["d2", "c3"],
        "keySquares": ["c1", "d2"]
    },
    {
        "id": "puz_pin_012",
        "fen": "r1bqk2r/ppp2ppp/2n1pn2/3p4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
        "moves": ["c1d2", "b4c3", "d2c3"],
        "rating": 980,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Recapturing on c3 with Bishop #12 ♝",
        "subtitle": "Bxc3 maintains a solid pawn structure!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Unpin with Bd2 and recapture on c3 with the Bishop.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. Bd2 unpinned the c3 Knight, and after 1...Bxc3, White played 2. Bxc3 avoiding doubled pawns.",
        "keyTakeaway": "Recapturing with a piece prevents damaged pawn structure.",
        "targetSquares": ["d2", "c3"],
        "keySquares": ["c1", "d2"]
    },
    {
        "id": "puz_pin_013",
        "fen": "r1bq1rk1/pp1n1ppp/4pn2/2pp4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQ - 0 1",
        "moves": ["c4d5", "e6d5", "e1g1"],
        "rating": 1020,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Central Tension Release #13 ♟",
        "subtitle": "cxd5 opens the e-file for future rook pins!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Exchange on d5 and castle to safety.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center File ♟",
        "learningSummary": "1. cxd5 resolved central tension and opened files for White's rooks after 2. O-O.",
        "keyTakeaway": "Opening files in front of uncastled enemy pieces creates deadly pin opportunities.",
        "targetSquares": ["d5", "g1"],
        "keySquares": ["c4", "e1"]
    },
    {
        "id": "puz_pin_014",
        "fen": "r1bqk2r/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c4d5", "e6d5", "e1g1"],
        "rating": 1060,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Symmetrical Center Resolution #14 ♟",
        "subtitle": "Open lines to create pins against Black's Knights!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Exchange on d5 and secure King safety.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Harmony ♟",
        "learningSummary": "1. cxd5 exd5 2. O-O solidified White's development while setting up pins along the d and e files.",
        "keyTakeaway": "Good positional play creates the conditions where tactical pins thrive.",
        "targetSquares": ["d5", "g1"],
        "keySquares": ["c4", "e1"]
    },
    {
        "id": "puz_pin_015",
        "fen": "r1bqk2r/pp1nbppp/2p1pn2/3p4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c4d5", "e6d5", "e1g1"],
        "rating": 1100,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Semi-Slav Pawn Exchange #15 ♟",
        "subtitle": "cxd5 isolates Black's d5 pawn!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Exchange on d5 and castle safely.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1. cxd5 exd5 2. O-O established kingside safety and freed White's c3 Knight from pins.",
        "keyTakeaway": "Simplifying central tension frees pinned pieces to join the attack.",
        "targetSquares": ["d5", "g1"],
        "keySquares": ["c4", "e1"]
    },
    {
        "id": "puz_pin_016",
        "fen": "r1b2rk1/pp1n1ppp/2p1pn2/q2p2B1/2PP4/2NBPN2/PP3PPP/R2QK2R w KQ - 0 1",
        "moves": ["g5f6", "d7f6", "e1g1"],
        "rating": 1140,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Removing the Defending Knight #16 ♝",
        "subtitle": "Bxf6 eliminates Black's key defender!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture on f6 to remove Black's knight defender and castle.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. Bxf6 eliminated the pinned Knight on f6. After 1...Nxf6, White castled 2. O-O.",
        "keyTakeaway": "Exchanging a pinned defender eliminates its influence over key central squares.",
        "targetSquares": ["f6", "g1"],
        "keySquares": ["g5", "e1"]
    },
    {
        "id": "puz_pin_017",
        "fen": "r1bqk2r/ppp2ppp/2n1pn2/3p4/1bPP4/1QN2N2/PP2PPPP/R1B1KB1R w KQkq - 0 1",
        "moves": ["a2a3", "b4c3", "b3c3"],
        "rating": 1180,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "easy",
        "title": "Challenging the Pin with a3 #17 ♟",
        "subtitle": "a3 forces Black's pinned Bishop to declare its intention!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Kick the pinning Bishop with a3 and recapture with the Queen.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. a3 forced Black's Bishop to capture on c3. White recaptured 2. Qxc3 holding the center with Queen dominance.",
        "keyTakeaway": "Pushing the rook pawn is the most direct way to challenge an annoying pin.",
        "targetSquares": ["a3", "c3"],
        "keySquares": ["a2", "b3"]
    },
    {
        "id": "puz_pin_018",
        "fen": "r1bqk2r/ppp1bppp/2n1pn2/3p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
        "moves": ["c4d5", "e6d5", "f1d3"],
        "rating": 1220,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Classical Bishop Development on d3 #18 ♝",
        "subtitle": "cxd5 and Bd3 aim directly at Black's kingside!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Exchange on d5 and develop the Bishop to d3.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Kingside Attack ⚔️",
        "learningSummary": "1. cxd5 exd5 2. Bd3 positioned the Bishop on the lethal b1-h7 diagonal.",
        "keyTakeaway": "Setting up batteries against the opponent's pinned pieces maximizes attacking pressure.",
        "targetSquares": ["d5", "d3"],
        "keySquares": ["c4", "f1"]
    },
    {
        "id": "puz_pin_019",
        "fen": "r1bqk2r/ppp2ppp/2n5/3np3/1b6/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c1d2", "b4c3", "b2c3"],
        "rating": 1260,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Defusing the c3 Pin #19 ♝",
        "subtitle": "Bd2 breaks the pin and recaptures safely!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Break the pin on c3 with Bd2.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Bishop ⚔️",
        "learningSummary": "1. Bd2 broke the pin on the c3 Knight. After 1...Bxc3, White recaptured 2. bxc3 maintaining solid central control.",
        "keyTakeaway": "Calm defensive moves that break pins preserve your pieces from tactical blows.",
        "targetSquares": ["d2", "c3"],
        "keySquares": ["c1", "b2"]
    },
    {
        "id": "puz_pin_020",
        "fen": "r4rk1/ppp2ppp/2n1pn2/8/3P4/2N2N2/PPP2PPP/R3R1K1 w - - 0 1",
        "moves": ["c3b5", "f8c8", "c2c4"],
        "rating": 1300,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Knight Pressure on c7 #20 ♞",
        "subtitle": "Nb5 attacks c7 and forces defensive concessions!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Attack c7 with Nb5 and reinforce the center with c4.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Space ♟",
        "learningSummary": "1. Nb5 forced Black to tie down the Rook with 1...Rfc8, and White expanded with 2. c4.",
        "keyTakeaway": "Pinning enemy pieces to defensive duties grants you complete freedom on the rest of the board.",
        "targetSquares": ["b5", "c4"],
        "keySquares": ["c3", "c2"]
    },
    {
        "id": "puz_pin_021",
        "fen": "r1bqk2r/pp1nbppp/2p1pn2/3p4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c4d5", "c6d5", "d1b3"],
        "rating": 1340,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Queen Battery Attack on b7 #21 ♛",
        "subtitle": "Qb3 attacks b7 and pins the queenside!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Play Qb3 to target the weakened b7 pawn.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Pressure ♟",
        "learningSummary": "1. cxd5 cxd5 2. Qb3 targeted Black's loose b7 pawn with strong Queenside initiative.",
        "keyTakeaway": "Pinning enemy pawns along ranks and diagonals creates long-term structural targets.",
        "targetSquares": ["d5", "b3"],
        "keySquares": ["c4", "d1"]
    },
    {
        "id": "puz_pin_022",
        "fen": "r1bqk2r/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PP2BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c4d5", "c5d4", "f3d4"],
        "rating": 1380,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Master Central Exchange Sequence #22 ♟",
        "subtitle": "Nxd4 establishes a commanding central post!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Resolve central captures and dominate d4 with the Knight.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Outpost ♞",
        "learningSummary": "1. cxd5 cxd4 2. Nxd4 centralized the Knight and exploited Black's pinned pieces.",
        "keyTakeaway": "Central exchanges clarify the position and leave you with superior piece activity.",
        "targetSquares": ["d5", "d4"],
        "keySquares": ["c4", "f3"]
    },
    {
        "id": "puz_pin_023",
        "fen": "r1bqk2r/pp1p1ppp/2n1pn2/8/1b1NP3/2N5/PPP1BPPP/R1BQK2R b KQkq - 0 1",
        "moves": ["f6e4", "d4c6", "b7c6"],
        "rating": 1420,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Black Central Pawn Snatch on e4 #23 ♟",
        "subtitle": "Nxe4 exploits the absolute pin on the c3 Knight!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture on e4 using the pin on c3.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1...Nxe4 won the e4 pawn because White's c3 Knight was pinned to the King by the b4 Bishop!",
        "keyTakeaway": "Pieces pinned to the King cannot capture attackers.",
        "targetSquares": ["e4", "c6"],
        "keySquares": ["f6", "b7"]
    },
    {
        "id": "puz_pin_024",
        "fen": "r2qk2r/ppp2ppp/2n1bn2/3p4/3P4/2N2N2/PPP1BPPP/R1BQK2R w KQkq - 0 1",
        "moves": ["c1g5", "h7h6", "g5f6"],
        "rating": 1460,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "medium",
        "title": "Bg5 Pin on the Kingside #24 📌",
        "subtitle": "Bg5 pins the f6 Knight to the Queen!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Pin the f6 Knight and capture it cleanly.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. Bg5 pinned Black's f6 Knight, and after 1...h6, White captured 2. Bxf6 winning the knight.",
        "keyTakeaway": "Pinning and exchanging on f6 weakens the enemy king's pawn shield.",
        "targetSquares": ["g5", "f6"],
        "keySquares": ["c1", "g5"]
    },
    {
        "id": "puz_pin_025",
        "fen": "r1bqk2r/pppp1ppp/2n2n2/4p3/3PP3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1",
        "moves": ["d4e5", "f6g4", "c1f4"],
        "rating": 1500,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "hard",
        "title": "Center Pawn Win and Consolidation #25 ♟",
        "subtitle": "dxe5 wins the e5 pawn and defends with Bf4!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Win the e5 pawn and defend the center with Bf4.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Pawn ♟",
        "learningSummary": "1. dxe5 won Black's e5 pawn. When Black attacked with 1...Ng4, White reinforced 2. Bf4 cleanly.",
        "keyTakeaway": "Central pawn advantages translate into winning endgames with proper defense.",
        "targetSquares": ["e5", "f4"],
        "keySquares": ["d4", "c1"]
    },
    {
        "id": "puz_pin_026",
        "fen": "r1bqk2r/ppp2ppp/2n5/3p4/3Pn3/2N2N2/PPP1BPPP/R1BQR1K1 w kq - 0 1",
        "moves": ["e2d3", "f7f5", "d3e4"],
        "rating": 1550,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "hard",
        "title": "Piling on the Pinned e4 Knight #26 📌",
        "subtitle": "Bd3 attacks the pinned Knight along the e-file!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Attack the pinned e4 Knight with Bd3 and capture it.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. Bd3 pinned Black's e4 Knight to the King on e8. After 1...f5, White captured 2. Bxe4 winning the piece.",
        "keyTakeaway": "Attacking an immobilized piece on an open file ensures winning it.",
        "targetSquares": ["d3", "e4"],
        "keySquares": ["e2", "d3"]
    },
    {
        "id": "puz_pin_027",
        "fen": "r2qk2r/ppp2ppp/2n1pn2/3p4/3P2b1/2N1PN2/PPP1BPPP/R1BQK2R b KQkq - 0 1",
        "moves": ["g4f3", "e2f3", "e8g8"],
        "rating": 1600,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "hard",
        "title": "Black Elimination of White's Defender #27 ♝",
        "subtitle": "...Bxf3 eliminates White's central guardian!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Capture on f3 and castle into safety.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1...Bxf3 eliminated the f3 Knight. After 2. Bxf3, Black castled 2...O-O with solid harmony.",
        "keyTakeaway": "Trading off an active pinning piece resolves kingside pressure cleanly.",
        "targetSquares": ["f3", "g8"],
        "keySquares": ["g4", "e8"]
    },
    {
        "id": "puz_pin_028",
        "fen": "r1bqk2r/ppp2ppp/2n5/3p4/3P4/2N2N2/PPP1RPPP/R1BQ2K1 b kq - 0 1",
        "moves": ["c8e6", "c1g5", "d8d7"],
        "rating": 1650,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "hard",
        "title": "Interposing the Bishop Against Rook Check #28 📌",
        "subtitle": "Be6 blocks the check and connects pieces!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Block the e-file check with ...Be6 and coordinate defense with ...Qd7.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Solid Blockade 🛡️",
        "learningSummary": "1...Be6 blocked the e-file check. When White played 2. Bg5, Black defended calmly with 2...Qd7.",
        "keyTakeaway": "Interposing a well-defended piece on the file blunts the enemy attack.",
        "targetSquares": ["e6", "d7"],
        "keySquares": ["c8", "d8"]
    },
    {
        "id": "puz_pin_029",
        "fen": "r1b1k2r/ppp2ppp/2n1pn2/3q4/3P4/2N2N2/PPP2PPP/R1BQKB1R b KQkq - 0 1",
        "moves": ["d5d6", "f1d3", "e8g8"],
        "rating": 1700,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "hard",
        "title": "Repositioning the Queen Out of Danger #29 ♛",
        "subtitle": "Qd6 steps out of the central attack line!",
        "playerColor": "b",
        "solutionPlies": 3,
        "tacticalGoal": "Retreat the Queen to d6 and castle safely.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Solid Position 🛡️",
        "learningSummary": "1...Qd6 stepped away from the Knight attack, and after 2. Bd3, Black secured the King 2...O-O.",
        "keyTakeaway": "Never leave your Queen on an open file where discovery pins can strike.",
        "targetSquares": ["d6", "g8"],
        "keySquares": ["d5", "e8"]
    },
    {
        "id": "puz_pin_030",
        "fen": "r2qk2r/ppp1bppp/2n1pn2/3p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 1",
        "moves": ["f1d3", "d5c4", "d3c4"],
        "rating": 1750,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "hard",
        "title": "Master Pawn Recapture on c4 #30 ♝",
        "subtitle": "Bxc4 controls the center and prepares kingside castle!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Develop the Bishop to d3 and recapture on c4 with tempo.",
        "tacticalReward": "win_pawn",
        "outcomeAdvantage": "+1 Center Control ⚔️",
        "learningSummary": "1. Bd3 developed the Bishop. When Black exchanged 1...dxc4, White recaptured 2. Bxc4 with great piece activity.",
        "keyTakeaway": "Recapturing with the Bishop develops pieces with tempo.",
        "targetSquares": ["d3", "c4"],
        "keySquares": ["f1", "d3"]
    },
    {
        "id": "puz_pin_031",
        "fen": "r1bqk2r/pppp1ppp/2n2n2/3Pp3/1b2P3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1",
        "moves": ["d5c6", "b7c6", "c1d2"],
        "rating": 1820,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "expert",
        "title": "Counter-Strike Against the Pinned Knight #31 ♟",
        "subtitle": "dxc6 captures the Knight while White is pinned!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Capture on c6 with the pawn and neutralize the pin with Bd2.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. dxc6 won Black's Knight. After 1...bxc6, White played 2. Bd2 neutralizing the pin completely.",
        "keyTakeaway": "An attack by a pawn on a pinned piece cannot be stopped by counter-pins.",
        "targetSquares": ["c6", "d2"],
        "keySquares": ["d5", "c1"]
    },
    {
        "id": "puz_pin_032",
        "fen": "r1b1k2r/pppp1ppp/8/8/4n3/2P5/PP3PPP/R1B1KB1R w KQkq - 0 1",
        "moves": ["f1d3", "d7d5", "d3e4"],
        "rating": 1900,
        "ratingDeviation": 80,
        "themes": ["pin", "captures_checks_threats"],
        "primaryTheme": "pin",
        "difficulty": "expert",
        "title": "Endgame Knight Removal with Bd3 #32 ♝",
        "subtitle": "Bxe4 removes Black's centralized knight!",
        "playerColor": "w",
        "solutionPlies": 3,
        "tacticalGoal": "Attack the e4 Knight with Bd3 and capture it cleanly.",
        "tacticalReward": "win_minor_piece",
        "outcomeAdvantage": "+3 Knight ⚔️",
        "learningSummary": "1. Bd3 attacked the centralized e4 Knight, and after 1...d5, White captured 2. Bxe4 heading into a won endgame.",
        "keyTakeaway": "Eliminating the enemy's most advanced piece transitions into a favorable endgame.",
        "targetSquares": ["d3", "e4"],
        "keySquares": ["f1", "d3"]
    }
]

run_pack_validator('pins.json', 'PIN_DATA', PINS)

